### ISSUE TITLE
tabulate issues

### ISSUE THREAD

**Issue by rosiorulilia** [ptimmons/128t-analyzer#18]
128T 4.5.2 - I have issue with script even if tabulate is installed:

[root@NAME]# pip show tabulate
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Name: tabulate
Version: 0.8.7
Summary: Pretty-print tabular data
Home-page: https://github.com/astanin/python-tabulate
Author: Sergey Astanin
Author-email: s.astanin@gmail.com
License: MIT
Location: /usr/lib/python2.7/site-packages
Requires:
Required-by:

[root@NAME]#  analyzer.py --help
Traceback (most recent call last):
  File "/usr/local/bin/analyzer.py", line 18, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'

**Comment by ptimmons** [comment]
Hi. The script uses python3, it looks like you installed tabulate using python2.

Can you try pip3 install tabulate?

**Comment by rosiorulilia** [comment]
# pip3 install tabulate 
-bash: pip3: command not found

I tried and install python3 but there are some other warnings
# yum install python34-pip.noarch
--> Finished Dependency Resolution
Error: Package: 128T-manifest-4.5.2.1.el7-1.x86_64 (installed)
           Requires: python3-libs = 3.6.8-13.el7
           Removing: python3-libs-3.6.8-13.el7.x86_64 (installed)
               python3-libs = 3.6.8-13.el7
           Updated By: python3-libs-3.6.8-17.el7.x86_64 (128tech-release)
               python3-libs = 3.6.8-17.el7
           Available: python3-libs-3.6.8-10.el7.x86_64 (128tech-local-saved)
               python3-libs = 3.6.8-10.el7
Error: python3 conflicts with python34-3.4.9-1.el7.x86_64
Error: Package: 128T-manifest-4.5.2.1.el7-1.x86_64 (installed)
           Requires: python3 = 3.6.8-13.el7
           Removing: python3-3.6.8-13.el7.x86_64 (installed)
               python3 = 3.6.8-13.el7
           Updated By: python3-3.6.8-17.el7.x86_64 (128tech-release)
               python3 = 3.6.8-17.el7
           Available: python3-3.6.8-10.el7.x86_64 (128tech-local-saved)
               python3 = 3.6.8-10.el7
Error: python3-libs conflicts with python34-libs-3.4.9-1.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Can you please provide the exact packages that are needed?

**Comment by ptimmons** [comment]
Try `easy_install-3.6 pip` to get pip3 on there. After that, use pip3 to install tabulate.
