### ISSUE TITLE
how to analyze router's session

### ISSUE THREAD

**Issue by hayleyshim** [ptimmons/128t-analyzer#20]
![image](https://user-images.githubusercontent.com/8789789/100700433-cb36f700-33e0-11eb-917e-a93368d76ada.png)

Hello,
I want to use this code to analyze the router's session.

Like the picture, I put the router name 's' and node name 's1' which I use to test.
But, it cause some error following the below.

> Error code 

**Traceback (most recent call last):
  File "/usr/local/bin/analyzer.py", line 385, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/analyzer.py", line 205, in main
    if loopSessions['data']['allRouters']['nodes'][0]['nodes']['nodes'][0]['flowEntries']['pageInfo']['hasNextPage']:
KeyError: 'data'**

In this case, Do I need to put other argument value?

**Comment by ptimmons** [comment]
You've installed the script on the same host where the 128T conductor is running? If so, what version of 128T is installed?

**Comment by hayleyshim** [comment]
Yes, I installed the script on the same host which 128T conductor is running.
I installed version 4.3.10.

**Comment by ptimmons** [comment]
Ahh! I see. Retrieving sessions from the Conductor in "online mode" requires that the conductor has its GraphQL API exposed on a specific port. The port changed between 4.3 and 4.4/4.5. I am not going to fix it for 4.3, but there are other changes coming soon that will require a new version of the analyzer script. When that happens I'll need to rework this whole area, and can revisit the issue.

Until then, please use the script in "offline mode" and report any problems. Sorry for the inconvenience!!!! I've updated the README file to explicitly mention the version requirements.

**Comment by hayleyshim** [comment]
> Ahh! I see. Retrieving sessions from the Conductor in "online mode" requires that the conductor has its GraphQL API exposed on a specific port. The port changed between 4.3 and 4.4/4.5. I am not going to fix it for 4.3, but there are other changes coming soon that will require a new version of the analyzer script. When that happens I'll need to rework this whole area, and can revisit the issue.
> 
> Until then, please use the script in "offline mode" and report any problems. Sorry for the inconvenience!!!! I've updated the README file to explicitly mention the version requirements.

I got it. Thanks!
